# Generated by Django 2.2.8 on 2019-12-15 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200, unique=True, verbose_name='Feed URL')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Feed title')),
                ('updated', models.DateTimeField(null=True, verbose_name='Feed origin data update date')),
                ('modified_dt', models.DateTimeField(auto_now=True, verbose_name='Internal update date')),
                ('creation_dt', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('gone', models.BooleanField(default=False, verbose_name='Gone forever')),
                ('failed_tries', models.PositiveIntegerField(default=0, verbose_name='Amount of consecutive failed parsing tries')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['modified_dt'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200, verbose_name='Entry URL')),
                ('title', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('content', models.TextField(verbose_name='Complete content')),
                ('updated', models.DateTimeField(null=True, verbose_name='Update time according to source')),
                ('bookmarks', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeds.Feed')),
            ],
            options={
                'ordering': ['updated'],
            },
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.UniqueConstraint(fields=('link', 'feed'), name='unique_entry_feed'),
        ),
    ]
